### ISSUE TITLE
vall-e How to run on macos m1

### ISSUE THREAD

**Issue by johnny-yu** [enhuiz/vall-e#100]
1. AssertionError: Torch not compiled with CUDA enabled
 vi  /usr/local/lib/python3.10/site-packages/vall_e/__main__.py on line 18
     parser.add_argument("--device", default="cuda") -->
     parser.add_argument("--device", default="cpu")

_pickle.UnpicklingError: could not find MARK

**Comment by johnny-yu** [comment]
The above issue has been resolved, it is a relative directory issue； `cuda change cpu`
~/config
~/data
~/nltk_data
`vi  ~/data/test/ar.yml. 
data_dirs: [data/test]`
 parameter should be equal to the file path where it is located
1.ok
2.ok
3.ok
but 、5.`python -m vall_e.train  yaml=data/test/ar.yml` on the macOS  m1
RuntimeError: Distributed package doesn't have NCCL built in
How to solve it ？
